import { callCommand } from './tauri';
import type {
  AppStatusDto,
  BackupDto,
  CustomerBalanceDto,
  CustomerDto,
  CustomerProductRuleDto,
  DailyProfitSummary,
  DocumentDto,
  ImportResult,
  InventoryReportRowDto,
  InboundRecordDto,
  MonthlyCreditDto,
  OrderDetailDto,
  OrderDto,
  PaymentRecordDto,
  ProfitAnalyticsRequest,
  ProfitAnalyticsResponse,
  PrintStatusDto,
  ProductDto,
  QuotePreviewDto,
  SettingDto,
  SupplierDto
} from '../shared/types';

export const api = {
  status: () => callCommand<AppStatusDto>('get_app_status'),
  products: (filter?: Record<string, unknown>) => callCommand<ProductDto[]>('list_products', { filter }),
  createProduct: (payload: Record<string, unknown>) => callCommand<ProductDto>('create_product', { payload }),
  updateProduct: (id: number, payload: Record<string, unknown>) => callCommand<ProductDto>('update_product', { id, payload }),
  disableProduct: (id: number) => callCommand<boolean>('disable_product', { id }),
  findProductByBarcode: (barcode: string) => callCommand<ProductDto | null>('find_product_by_barcode', { barcode }),
  customers: (filter?: Record<string, unknown>) => callCommand<CustomerDto[]>('list_customers', { filter }),
  createCustomer: (payload: Record<string, unknown>) => callCommand<CustomerDto>('create_customer', { payload }),
  updateCustomer: (id: number, payload: Record<string, unknown>) => callCommand<CustomerDto>('update_customer', { id, payload }),
  disableCustomer: (id: number) => callCommand<boolean>('disable_customer', { id }),
  suppliers: (filter?: Record<string, unknown>) => callCommand<SupplierDto[]>('list_suppliers', { filter }),
  createSupplier: (payload: Record<string, unknown>) => callCommand<SupplierDto>('create_supplier', { payload }),
  updateSupplier: (id: number, payload: Record<string, unknown>) => callCommand<SupplierDto>('update_supplier', { id, payload }),
  disableSupplier: (id: number) => callCommand<boolean>('disable_supplier', { id }),
  createInbound: (payload: Record<string, unknown>) => callCommand('create_inbound', { payload }),
  inboundRecords: (filter?: Record<string, unknown>) => callCommand<InboundRecordDto[]>('list_inbound_records', { filter }),
  previewQuote: (payload: Record<string, unknown>) => callCommand<QuotePreviewDto>('preview_quote', { payload }),
  saveOrder: (payload: Record<string, unknown>) => callCommand('save_order', { payload }),
  order: (id: number) => callCommand<OrderDetailDto>('get_order', { id }),
  orders: (filter?: Record<string, unknown>) => callCommand<OrderDto[]>('list_orders', { filter }),
  exportOrder: (orderId: number) => callCommand<string>('export_order_document', { orderId }),
  printOrder: (orderId: number) => callCommand<string>('print_order_document', { orderId }),
  printOrderWithOptions: (orderId: number, payload?: Record<string, unknown>) =>
    callCommand<PrintStatusDto>('print_order_document_with_options', { orderId, payload }),
  voidOrder: (id: number, payload?: Record<string, unknown>) => callCommand<OrderDto>('void_order', { id, payload }),
  rules: (filter?: Record<string, unknown>) => callCommand<CustomerProductRuleDto[]>('list_customer_product_rules', { filter }),
  saveRule: (payload: Record<string, unknown>) => callCommand<number>('save_customer_product_rule', { payload }),
  disableRule: (id: number) => callCommand<boolean>('disable_customer_product_rule', { id }),
  deleteRule: (id: number) => callCommand<boolean>('delete_customer_product_rule', { id }),
  monthlyCredits: (filter?: Record<string, unknown>) => callCommand<MonthlyCreditDto[]>('list_monthly_credits', { filter }),
  availableMonthlyCredits: (customerId: number, category: string, orderDate: string) =>
    callCommand<MonthlyCreditDto[]>('get_available_monthly_credits', { customerId, category, orderDate }),
  closeMonthlyCredit: (id: number) => callCommand<boolean>('close_monthly_credit', { id }),
  voidMonthlyCredit: (id: number) => callCommand<boolean>('void_monthly_credit', { id }),
  customerBalances: (filter?: Record<string, unknown>) => callCommand<CustomerBalanceDto[]>('list_customer_balances', { filter }),
  paymentRecords: (filter?: Record<string, unknown>) => callCommand<PaymentRecordDto[]>('list_payment_records', { filter }),
  createPayment: (payload: Record<string, unknown>) => callCommand<PaymentRecordDto>('create_payment', { payload }),
  voidPayment: (id: number) => callCommand<PaymentRecordDto>('void_payment', { id }),
  dailyProfit: (date: string) => callCommand<DailyProfitSummary>('get_daily_profit_summary', { date }),
  profitAnalytics: (request: ProfitAnalyticsRequest) =>
    callCommand<ProfitAnalyticsResponse>('get_profit_analytics', { request }),
  profitRecords: (filter?: Record<string, unknown>) => callCommand<OrderDto[]>('list_profit_records', { filter }),
  inventoryReport: (filter?: Record<string, unknown>) => callCommand<InventoryReportRowDto[]>('list_inventory_report', { filter }),
  documents: (filter?: Record<string, unknown>) => callCommand<DocumentDto[]>('list_documents', { filter }),
  openDocument: (documentId: number) => callCommand<string>('open_document', { documentId }),
  exportDocument: (orderId: number) => callCommand<string>('export_document', { orderId }),
  printDocument: (documentId: number, payload?: Record<string, unknown>) =>
    callCommand<PrintStatusDto>('print_document', { documentId, payload }),
  exportData: (payload: Record<string, unknown>) => callCommand<string>('export_data', { payload }),
  openExportsFolder: () => callCommand<string>('open_exports_folder'),
  openLogsFolder: () => callCommand<string>('open_logs_folder'),
  importExcel: (filePath: string) => callCommand<ImportResult>('import_excel', { filePath }),
  importStatus: () => callCommand<ImportResult | null>('get_import_status'),
  backup: () => callCommand<string>('create_backup'),
  backups: () => callCommand<BackupDto[]>('list_backups'),
  openBackupFolder: () => callCommand<string>('open_backup_folder'),
  settings: () => callCommand<SettingDto[]>('list_settings'),
  saveSettings: (payload: Record<string, unknown>) => callCommand<boolean>('save_settings', { payload }),
  printers: () => callCommand<string[]>('list_printers')
};
